### ISSUE TITLE
Right alignment

### ISSUE THREAD

**Issue by Azuka** [M1ke/jquery-datepicker#1]
I'm having this issue http://stackoverflow.com/questions/8254219/date-picker-is-shown-in-the-left-offset-how-to-show-it-in-the-right where the date picker doesn't look good on right-aligned elements.

Do you have any suggestions on what I can do to help with the positioning?

**Comment by M1ke** [comment]
That issue is for the jQuery UI datepicker, do you have a code example that you can show me?

The solution on the jQUI question was to do with the plug-in itself, so if it isn't possible to manually change alignment I can look at adding it as a new feature in this datepicker.

**Comment by Azuka** [comment]
I was able to make changes that got it working. I can clone your repo and
submit a pull request.

**Comment by M1ke** [comment]
Sure, submit and I'll test and merge.
